[package]
name = "rings-runtime"
description = "Guest extension runtime model and proof adapters for Rings Network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["std"]
std = ["rings-core/std"]
browser = ["rings-core/wasm"]
risc0-proof = [
    "dep:rings-proofs",
    "rings-proofs/risc0-proof",
]
risc0-prove = [
    "risc0-proof",
    "rings-proofs/risc0-prove",
]
wasm-proof = [
    "dep:rings-proofs",
    "rings-proofs/wasm-proof",
]

[dependencies]
bincode = "1.3.3"
bytes = { version = "1.2.1", features = ["serde"] }
rings-core = { workspace = true, default-features = false }
rings-proofs = { workspace = true, optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.70"
thiserror = "1"

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
