#![deny(missing_docs, warnings)]
//! Deterministic generator for the Rings geometric construction mark.
//!
//! The geometry and palette are derived from a small set of dimensionless
//! inputs. Generated files are repository artifacts, never design sources.

mod color;
mod model;
mod svg;

use std::error::Error;
use std::fmt;

use color::Palette;
use model::{GearModel, GeometryError, Spec};

/// A repository-relative asset generated by the canonical construction.
#[derive(Debug, Eq, PartialEq)]
pub struct GeneratedAsset {
    path: &'static str,
    contents: String,
}

impl GeneratedAsset {
    /// Returns the repository-relative output path.
    #[must_use]
    pub const fn path(&self) -> &'static str {
        self.path
    }

    /// Returns the complete UTF-8 artifact contents.
    #[must_use]
    pub fn contents(&self) -> &str {
        &self.contents
    }
}

/// A failure to construct the canonical logo assets.
#[derive(Debug)]
pub struct LogoError {
    message: String,
}

impl fmt::Display for LogoError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl Error for LogoError {}

impl From<GeometryError> for LogoError {
    fn from(error: GeometryError) -> Self {
        Self {
            message: format!("invalid logo geometry: {error}"),
        }
    }
}

impl From<color::ColorError> for LogoError {
    fn from(error: color::ColorError) -> Self {
        Self {
            message: format!("invalid logo palette: {error}"),
        }
    }
}

/// Generates every canonical Rings logo asset from the mathematical model.
///
/// # Errors
///
/// Returns an error if a construction invariant is violated or a palette role
/// cannot satisfy its required contrast ratio.
pub fn generate_assets() -> Result<Vec<GeneratedAsset>, LogoError> {
    let model = GearModel::new(Spec::rings())?;
    let light = Palette::light(&model)?;
    let dark = Palette::dark(&model)?;
    let light_svg = svg::render_fixed(&model, &light, "light background");
    let dark_svg = svg::render_fixed(&model, &dark, "dark background");
    let adaptive_svg = svg::render_adaptive(&model, &light, &dark);
    let specification = svg::render_specification(&model, &light, &dark);
    let social_card = svg::render_social_card(&model, &dark);

    Ok(vec![
        GeneratedAsset {
            path: "assets/logo/rings.svg",
            contents: light_svg,
        },
        GeneratedAsset {
            path: "assets/logo/rings-white.svg",
            contents: dark_svg.clone(),
        },
        GeneratedAsset {
            path: "assets/logo/rings-spec.json",
            contents: specification,
        },
        GeneratedAsset {
            path: "frontend/assets/icons/rings.svg",
            contents: dark_svg.clone(),
        },
        GeneratedAsset {
            path: "frontend/assets/icons/favicon.svg",
            contents: adaptive_svg.clone(),
        },
        GeneratedAsset {
            path: "frontend/assets/social/card.svg",
            contents: social_card,
        },
        GeneratedAsset {
            path: "docs/src/assets/rings.svg",
            contents: dark_svg,
        },
        GeneratedAsset {
            path: "docs/theme/favicon.svg",
            contents: adaptive_svg,
        },
    ])
}

#[cfg(test)]
mod tests {
    use super::generate_assets;

    #[test]
    fn canonical_generation_is_deterministic() {
        let first = generate_assets();
        let second = generate_assets();
        assert!(first.is_ok());
        assert!(second.is_ok());
        if let (Ok(first), Ok(second)) = (first, second) {
            assert_eq!(first, second);
        }
    }

    #[test]
    fn all_svg_assets_are_self_describing_and_finite() {
        let assets = generate_assets();
        assert!(assets.is_ok());
        if let Ok(assets) = assets {
            for asset in assets.iter().filter(|asset| asset.path().ends_with(".svg")) {
                assert!(asset.contents().starts_with("<svg"));
                assert!(asset.contents().contains("<metadata>"));
                assert!(!asset.contents().contains("NaN"));
                assert!(!asset.contents().contains("Infinity"));
            }
        }
    }
}
