//! Deterministic SVG and machine-readable specification rendering.

use std::fmt::Write as _;

use crate::color::Paint;
use crate::color::Palette;
use crate::model::GearModel;
use crate::model::Point;

pub(crate) fn render_fixed(model: &GearModel, palette: &Palette, ground: &str) -> String {
    render_svg(model, fixed_style(palette), ground)
}

pub(crate) fn render_adaptive(model: &GearModel, light: &Palette, dark: &Palette) -> String {
    let style = format!(
        ".primary{{stroke:{}}}.accent{{stroke:{}}}.signal{{fill:{}}}.guide{{stroke:{}}}\n\
         @media(prefers-color-scheme:dark){{.primary{{stroke:{}}}.accent{{stroke:{}}}\
         .signal{{fill:{}}}.guide{{stroke:{}}}}}",
        light.primary.hex,
        light.accent.hex,
        light.signal.hex,
        light.guide.hex,
        dark.primary.hex,
        dark.accent.hex,
        dark.signal.hex,
        dark.guide.hex,
    );
    render_svg(model, style, "adaptive background")
}

pub(crate) fn render_social_card(model: &GearModel, palette: &Palette) -> String {
    let logo = embedded_logo(model, palette);
    format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <!-- Generated by rings-logo. Render with `rsvg-convert card.svg -o rings-card.png`. -->
  <metadata>{}</metadata>
  <defs>
    <linearGradient id="page" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#fbf4e6"/>
      <stop offset="1" stop-color="#f3ead8"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#page)"/>
  <g fill="none" stroke="#dfd0b7" stroke-width="2">
    <circle cx="1010" cy="315" r="250"/>
    <circle cx="1010" cy="315" r="190" stroke-dasharray="6 10"/>
    <circle cx="1010" cy="315" r="130"/>
  </g>
  <g fill="#111827">
    <circle cx="1010" cy="65" r="9"/><circle cx="1226" cy="190" r="9"/>
    <circle cx="1226" cy="440" r="9"/><circle cx="1010" cy="565" r="9"/>
    <circle cx="794" cy="440" r="9"/><circle cx="794" cy="190" r="9"/>
  </g>
  <circle cx="1010" cy="65" r="14" fill="none" stroke="#b42318" stroke-width="3"/>
  <rect x="88" y="84" width="112" height="112" rx="26" fill="#111827"/>
{logo}
  <text x="224" y="134" font-family="Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="34" font-weight="700" fill="#101828">Rings Network</text>
  <text x="224" y="172" font-family="Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="24" fill="#736453">Browser-native P2P</text>
  <text x="88" y="290" font-family="'SFMono-Regular', Menlo, Consolas, monospace" font-size="22" font-weight="700" letter-spacing="3" fill="#b42318">RINGS NETWORK</text>
  <text font-family="Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="70" font-weight="800" fill="#101828">
    <tspan x="84" y="366">A P2P network for</tspan><tspan x="84" y="446">the sovereign age.</tspan>
  </text>
  <text font-family="Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="26" fill="#475467">
    <tspan x="88" y="506">Browser tabs and native daemons join one overlay, find each other by DID,</tspan>
    <tspan x="88" y="542">and talk over direct WebRTC datachannels routed by a Chord DHT.</tspan>
  </text>
  <g font-family="'SFMono-Regular', Menlo, Consolas, monospace" font-size="20" font-weight="700" fill="#344054">
    <text x="88" y="596">WEBRTC · CHORD DHT · DID · WASM · AGPL-3.0</text>
    <text x="1112" y="596" text-anchor="end" fill="#b42318">rings.rs</text>
  </g>
</svg>
"##,
        metadata(model),
    )
}

fn embedded_logo(model: &GearModel, palette: &Palette) -> String {
    let radius = viewbox_radius(model);
    let size = 2.0 * radius;
    format!(
        "  <svg x=\"100\" y=\"96\" width=\"88\" height=\"88\" viewBox=\"-{} -{} {} {}\">\n\
         <style>{}</style><defs><path id=\"tooth\" d=\"{}\"/></defs>\n{}</svg>",
        format_number(radius),
        format_number(radius),
        format_number(size),
        format_number(size),
        fixed_style(palette),
        tooth_path(model),
        geometry_fragment(model),
    )
}

fn fixed_style(palette: &Palette) -> String {
    format!(
        ".primary{{stroke:{}}}.accent{{stroke:{}}}.signal{{fill:{}}}.guide{{stroke:{}}}",
        palette.primary.hex, palette.accent.hex, palette.signal.hex, palette.guide.hex,
    )
}

fn render_svg(model: &GearModel, style: String, ground: &str) -> String {
    let tooth = tooth_path(model);
    let geometry = geometry_fragment(model);
    let radius = viewbox_radius(model);
    let size = format_number(2.0 * radius);
    format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1024\" height=\"1024\" \
         viewBox=\"-{} -{} {size} {size}\" role=\"img\" aria-labelledby=\"title desc\">\n\
         <title id=\"title\">Rings geometric construction mark, {ground}</title>\n\
         <desc id=\"desc\">A thirty-tooth involute gear, five bores on a regular pentagon, \
         construction circles, and a pentagon-derived geometric R.</desc>\n\
         <metadata>{}</metadata>\n<style>{style}</style>\n\
         <defs><path id=\"tooth\" d=\"{tooth}\"/></defs>\n{geometry}</svg>\n",
        format_number(radius),
        format_number(radius),
        metadata(model),
    )
}

fn geometry_fragment(model: &GearModel) -> String {
    let module = model.spec.module;
    let holes = f64::from(model.spec.hole_count);
    let mut output = String::new();
    let _ = writeln!(
        output,
        "<g class=\"guide\" fill=\"none\" stroke-width=\"{}\">",
        format_number(module / (2.0 * holes)),
    );
    let _ = writeln!(
        output,
        "  <path d=\"M -{} 0 H {} M 0 -{} V {}\"/>",
        format_number(model.outer_radius + module),
        format_number(model.outer_radius + module),
        format_number(model.outer_radius + module),
        format_number(model.outer_radius + module),
    );
    let _ = writeln!(
        output,
        "  <circle r=\"{}\"/>",
        format_number(model.outer_radius)
    );
    append_circle(
        &mut output,
        model.pitch_radius,
        module * (holes - 3.0) / holes,
        module / 2.0,
    );
    append_circle(&mut output, model.base_radius, module / holes, module / 2.0);
    append_circle(
        &mut output,
        model.root_radius,
        module * (holes - 1.0) / holes,
        module * (holes - 3.0) / holes,
    );
    let _ = writeln!(
        output,
        "  <circle r=\"{}\"/>",
        format_number(model.aperture_radius)
    );
    append_circle(
        &mut output,
        model.hole_orbit,
        module * (holes - 2.0) / holes,
        module / 2.0,
    );
    let _ = writeln!(output, "  <polygon points=\"{}\"/>", polygon_points(model));
    let phase = GearModel::point(model.outer_radius, -std::f64::consts::PI / 2.0);
    let _ = writeln!(output, "  <path d=\"M 0 0 L {}\"/>", command_point(phase));
    output.push_str("</g>\n");

    let _ = writeln!(
        output,
        "<g class=\"primary\" fill=\"none\" stroke-width=\"{}\" stroke-linecap=\"square\" stroke-linejoin=\"miter\">",
        format_number(model.gear_outline_width),
    );
    for tooth in 0..model.spec.teeth {
        let rotation = 360.0 * f64::from(tooth) / f64::from(model.spec.teeth);
        let _ = writeln!(
            output,
            "  <use href=\"#tooth\" transform=\"rotate({})\"/>",
            format_number(rotation)
        );
    }
    output.push_str("</g>\n");

    let _ = writeln!(
        output,
        "<g class=\"accent\" fill=\"none\" stroke-width=\"{}\" stroke-linecap=\"butt\" stroke-linejoin=\"miter\">",
        format_number(model.gear_outline_width),
    );
    for hole in model.holes() {
        let _ = writeln!(
            output,
            "  <circle cx=\"{}\" cy=\"{}\" r=\"{}\"/>",
            format_number(hole.x),
            format_number(hole.y),
            format_number(model.hole_radius),
        );
    }
    let _ = writeln!(
        output,
        "  <path d=\"{}\" stroke-width=\"{}\"/>",
        glyph_path(model),
        format_number(model.glyph().stroke_width),
    );
    output.push_str("</g>\n<g class=\"signal\">\n");
    for hole in model.holes() {
        let _ = writeln!(
            output,
            "  <circle cx=\"{}\" cy=\"{}\" r=\"{}\"/>",
            format_number(hole.x),
            format_number(hole.y),
            format_number(model.hole_radius / holes),
        );
    }
    let _ = writeln!(
        output,
        "  <circle r=\"{}\"/>",
        format_number(model.hole_radius / (holes - 1.0))
    );
    output.push_str("</g>\n");
    output
}

fn append_circle(output: &mut String, radius: f64, dash: f64, gap: f64) {
    let _ = writeln!(
        output,
        "  <circle r=\"{}\" stroke-dasharray=\"{} {}\"/>",
        format_number(radius),
        format_number(dash),
        format_number(gap),
    );
}

fn tooth_path(model: &GearModel) -> String {
    let center = -std::f64::consts::PI / 2.0;
    let left_root = GearModel::point(model.root_radius, center - model.flank_rotation);
    let left_base = GearModel::point(model.base_radius, center - model.flank_rotation);
    let mut commands = format!(
        "M {} L {}",
        command_point(left_root),
        command_point(left_base)
    );

    for sample in 1..=model.flank_samples {
        let parameter =
            model.outer_involute_parameter * f64::from(sample) / f64::from(model.flank_samples);
        let (radius, angle) = model.polar_involute(parameter);
        let point = GearModel::point(radius, center - model.flank_rotation + angle);
        let _ = write!(commands, " L {}", command_point(point));
    }

    let (_, outer_angle) = model.polar_involute(model.outer_involute_parameter);
    let right_tip = GearModel::point(
        model.outer_radius,
        center + model.flank_rotation - outer_angle,
    );
    let _ = write!(
        commands,
        " A {} {} 0 0 1 {}",
        format_number(model.outer_radius),
        format_number(model.outer_radius),
        command_point(right_tip),
    );

    for sample in (0..model.flank_samples).rev() {
        let parameter =
            model.outer_involute_parameter * f64::from(sample) / f64::from(model.flank_samples);
        let (radius, angle) = model.polar_involute(parameter);
        let point = GearModel::point(radius, center + model.flank_rotation - angle);
        let _ = write!(commands, " L {}", command_point(point));
    }

    let right_root = GearModel::point(model.root_radius, center + model.flank_rotation);
    let next_left_root = GearModel::point(
        model.root_radius,
        center + model.tooth_pitch - model.flank_rotation,
    );
    let _ = write!(
        commands,
        " L {} A {} {} 0 0 1 {}",
        command_point(right_root),
        format_number(model.root_radius),
        format_number(model.root_radius),
        command_point(next_left_root),
    );
    commands
}

fn glyph_path(model: &GearModel) -> String {
    let glyph = model.glyph();
    format!(
        "M {} {} V -{} H {} A {} {} 0 0 1 {} {} H {} M {} {} L {} {}",
        format_number(glyph.stem_x),
        format_number(glyph.cap),
        format_number(glyph.cap),
        format_number(glyph.bowl_x),
        format_number(glyph.bowl_radius),
        format_number(glyph.bowl_radius),
        format_number(glyph.bowl_x),
        format_number(glyph.middle_y),
        format_number(glyph.stem_x),
        format_number(glyph.leg_start.x),
        format_number(glyph.leg_start.y),
        format_number(glyph.leg_end.x),
        format_number(glyph.leg_end.y),
    )
}

fn polygon_points(model: &GearModel) -> String {
    model
        .holes()
        .map(command_point)
        .collect::<Vec<_>>()
        .join(" ")
}

fn command_point(point: Point) -> String {
    format!("{},{}", format_number(point.x), format_number(point.y))
}

fn metadata(model: &GearModel) -> String {
    format!(
        "module={};teeth={};pressure-angle={}deg;pitch-radius={};base-radius={};\
         outer-radius={};root-radius={};aperture-radius={};bore-count={};\
         bore-orbit={};bore-radius={};gear-stroke={};r-stroke={};r-golden-ratio={};\
         r-leg-bore={};r-leg-angle={}deg",
        format_number(model.spec.module),
        model.spec.teeth,
        format_number(model.spec.pressure_angle_degrees),
        format_number(model.pitch_radius),
        format_number(model.base_radius),
        format_number(model.outer_radius),
        format_number(model.root_radius),
        format_number(model.aperture_radius),
        model.spec.hole_count,
        format_number(model.hole_orbit),
        format_number(model.hole_radius),
        format_number(model.gear_outline_width),
        format_number(model.glyph().stroke_width),
        format_number(model.glyph().golden_ratio),
        model.glyph().leg_bore_index,
        format_number(model.glyph().leg_angle_degrees),
    )
}

fn viewbox_radius(model: &GearModel) -> f64 {
    model.outer_radius + 2.0 * model.hole_radius
}

pub(crate) fn render_specification(model: &GearModel, light: &Palette, dark: &Palette) -> String {
    let document = format!(
        "{{\n  \"generator\": \"rings-logo\",\n  \"geometry\": {{\n    \"module\": {},\n    \"teeth\": {},\n    \"pressure_angle_degrees\": {},\n    \"pitch_radius\": {},\n    \"base_radius\": {},\n    \"outer_radius\": {},\n    \"root_radius\": {},\n    \"aperture_radius\": {},\n    \"bore_count\": {},\n    \"bore_orbit\": {},\n    \"bore_radius\": {},\n    \"teeth_per_bore_sector\": {},\n    \"flank_samples\": {}\n  }},\n  \"geometry_rules\": {{\n    \"aperture_radius\": \"2*bore_count*module\",\n    \"bore_orbit\": \"aperture_radius+2*module\",\n    \"bore_radius\": \"(bore_count-1)/bore_count*module\",\n    \"flank_samples\": \"teeth/bore_count*(bore_count-1)\",\n    \"viewbox_radius\": \"outer_radius+2*bore_radius\"\n  }},\n  \"glyph_rules\": {{\n    \"golden_ratio\": {},\n    \"vertical_extent\": \"aperture_radius/golden_ratio\",\n    \"stem_axis\": \"-aperture_radius/2\",\n    \"bowl_radius\": \"aperture_radius/(2*golden_ratio)\",\n    \"stroke_width\": \"aperture_radius/bore_count\",\n    \"leg_angle\": \"3/4*(360/bore_count)\",\n    \"leg_angle_degrees\": {}\n  }},\n  \"color_rules\": {{\n    \"space\": \"OKLCH converted to quantized sRGB\",\n    \"lightness_grid\": \"1/10000\",\n    \"rust_hue\": \"360/(2*bore_count)=36deg\",\n    \"signal_hue\": \"rust_hue+180=216deg\",\n    \"accent_chroma\": \"(bore_count-1)/teeth\",\n    \"guide_chroma\": \"1/teeth\",\n    \"neutral_chroma\": \"guide_chroma/golden_ratio^2\"\n  }},\n  \"palettes\": {{\n    \"light_background\": {},\n    \"dark_background\": {}\n  }}\n}}\n",
        format_number(model.spec.module),
        model.spec.teeth,
        format_number(model.spec.pressure_angle_degrees),
        format_number(model.pitch_radius),
        format_number(model.base_radius),
        format_number(model.outer_radius),
        format_number(model.root_radius),
        format_number(model.aperture_radius),
        model.spec.hole_count,
        format_number(model.hole_orbit),
        format_number(model.hole_radius),
        model.teeth_per_bore_sector(),
        model.flank_samples,
        format_number(model.glyph().golden_ratio),
        format_number(model.glyph().leg_angle_degrees),
        palette_json(light),
        palette_json(dark),
    );
    document
        .replace(
            "    \"stroke_width\": \"aperture_radius/bore_count\",",
            concat!(
                "    \"stroke_width\": \"aperture_radius/bore_count\",\n",
                "    \"gear_outline_width\": \"stroke_width/(bore_count-1)\",\n",
                "    \"glyph_to_gear_stroke_ratio\": \"bore_count-1\",",
            ),
        )
        .replace(
            "    \"leg_angle\": \"3/4*(360/bore_count)\",",
            &format!(
                "    \"leg_bore_index\": {},\n    \"leg_angle\": \"-90+leg_bore_index*(360/bore_count)\",",
                model.glyph().leg_bore_index
            ),
        )
}

fn palette_json(palette: &Palette) -> String {
    format!(
        "{{\n      \"primary\": {},\n      \"accent\": {},\n      \"signal\": {},\n      \"guide\": {}\n    }}",
        paint_json(&palette.primary),
        paint_json(&palette.accent),
        paint_json(&palette.signal),
        paint_json(&palette.guide),
    )
}

fn paint_json(paint: &Paint) -> String {
    format!(
        "{{\"hex\": \"{}\", \"oklch\": [{}, {}, {}], \"contrast\": {}, \"target\": {}}}",
        paint.hex,
        format_number(paint.lightness),
        format_number(paint.chroma),
        format_number(paint.hue),
        format_number(paint.contrast),
        format_number(paint.target_contrast),
    )
}

fn format_number(value: f64) -> String {
    let normalized = if value.abs() < 0.000_000_5 {
        0.0
    } else {
        value
    };
    let mut rendered = format!("{normalized:.6}");
    while rendered.ends_with('0') {
        rendered.pop();
    }
    if rendered.ends_with('.') {
        rendered.pop();
    }
    rendered
}

#[cfg(test)]
mod tests {
    use super::geometry_fragment;
    use super::tooth_path;
    use crate::model::GearModel;
    use crate::model::Spec;

    #[test]
    fn one_tooth_is_reused_at_exact_angular_pitch() {
        let model = GearModel::new(Spec::rings());
        assert!(model.is_ok());
        if let Ok(model) = model {
            let fragment = geometry_fragment(&model);
            assert_eq!(fragment.matches("<use href=\"#tooth\"").count(), 30);
            assert!(fragment.contains("transform=\"rotate(12)\""));
            assert!(!tooth_path(&model).contains("NaN"));
        }
    }
}
