#!/usr/bin/env node

/**
 * Packages the Trunk web build as a Chrome Manifest V3 extension.
 */

import { execFile } from "node:child_process";
import { access, cp, mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

/**
 * One icon output variant derived from the source Rings SVG.
 */
type IconState = {
  readonly file: string;
  readonly color: string;
};

/**
 * Options for generating extension HTML shells.
 */
type HtmlShellOptions = {
  readonly includeNodeBridge: boolean;
};

/** Copied artifact and its renderer exposure policy. */
type CopiedExtensionArtifact = {
  readonly kind: "copy";
  readonly source: string;
  readonly output: string;
  readonly exposure: "private" | "renderer";
};

/** Artifact generated by this packaging script. */
type GeneratedExtensionArtifact = {
  readonly kind: "generated";
  readonly output: string;
  readonly exposure: "private" | "renderer";
};

/** Browser-only artifact forbidden from the extension package. */
type ExcludedExtensionArtifact = {
  readonly kind: "excluded";
  readonly output: string;
};

/**
 * Finite policy for runtime modules and explicitly forbidden web-only outputs.
 * HTML shells, Trunk output, and icons retain their dedicated generators below.
 */
type ExtensionRuntimeArtifactPolicy = CopiedExtensionArtifact | GeneratedExtensionArtifact | ExcludedExtensionArtifact;

/**
 * Manifest V3 structure emitted for the packaged browser extension.
 */
type ChromeManifest = {
  readonly manifest_version: 3;
  readonly name: string;
  readonly short_name: string;
  readonly version: string;
  readonly description: string;
  readonly minimum_chrome_version: string;
  readonly icons: Record<string, string>;
  readonly action: {
    readonly default_title: string;
    readonly default_icon: Record<string, string>;
  };
  readonly background: {
    readonly service_worker: string;
    readonly type: "module";
  };
  readonly side_panel: {
    readonly default_path: string;
  };
  readonly options_page: string;
  readonly permissions: readonly string[];
  readonly host_permissions: readonly string[];
  readonly web_accessible_resources: readonly {
    readonly resources: readonly string[];
    readonly matches: readonly string[];
  }[];
  readonly content_security_policy: {
    readonly extension_pages: string;
    readonly sandbox: string;
  };
  readonly sandbox: {
    readonly pages: readonly string[];
  };
};

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = frontendProjectRoot(scriptDir);
const sourceDist = resolve(projectRoot, process.argv[2] ?? "dist");
const extensionDist = resolve(projectRoot, process.argv[3] ?? "dist-extension");
const execFileAsync = promisify(execFile);
const sourceIconSvg = join(projectRoot, "assets", "icons", "rings.svg");
const extensionAssets = resolve(projectRoot, ".generated", "extension-assets");
const staticExtensionAssets = resolve(projectRoot, "extension-assets");
const dependencyRoot = resolve(projectRoot, "..", "node_modules");
const moduleBundlerSourceArtifact = generatedArtifact("webview_worker_modules_source.js", "renderer");
const EXTENSION_RUNTIME_ARTIFACTS: readonly ExtensionRuntimeArtifactPolicy[] = [
  compiledArtifact("wallet_bridge.js", "private"),
  compiledArtifact("node_bridge.js", "private"),
  compiledArtifact("service_worker.js", "private"),
  compiledArtifact("extension_runtime.js", "private"),
  compiledArtifact("extension_webview_service_worker.js", "private"),
  compiledArtifact("extension_webview.js", "private"),
  compiledArtifact("extension_webview_frame.js", "renderer"),
  compiledArtifact("extension_webview_frame_boundary.js", "renderer"),
  compiledArtifact("extension_webview_nested.js", "renderer"),
  compiledArtifact("extension_webview_worker.js", "renderer"),
  compiledArtifact("extension_webview_xhr.js", "renderer"),
  compiledArtifact("webview_navigation_state.js", "private"),
  compiledArtifact("webview_protocol.js", "renderer"),
  compiledArtifact("webview_renderer_session.js", "renderer"),
  staticArtifact("webview.html", "private"),
  staticArtifact("webview_frame.html", "renderer"),
  staticArtifact("webview.css", "private"),
  copiedArtifact(join(projectRoot, "assets", "webview-worker-request.js"), "webview_request_body.js", "renderer"),
  copiedArtifact(
    resolve(projectRoot, "..", "crates", "webview", "src", "browser_runtime_transforms.mjs"),
    "webview_runtime_transforms.js",
    "renderer",
  ),
  copiedArtifact(join(dependencyRoot, "acorn", "dist", "acorn.mjs"), "acorn.mjs", "renderer"),
  copiedArtifact(join(dependencyRoot, "acorn", "LICENSE"), "LICENSE.acorn", "private"),
  copiedArtifact(join(dependencyRoot, "es-module-lexer", "dist", "lexer.asm.js"), "es-module-lexer.js", "renderer"),
  copiedArtifact(join(dependencyRoot, "es-module-lexer", "LICENSE"), "LICENSE.es-module-lexer", "private"),
  copiedArtifact(
    join(dependencyRoot, "@rollup", "browser", "dist", "es", "rollup.browser.js"),
    "rollup.browser.js",
    "renderer",
  ),
  copiedArtifact(
    join(dependencyRoot, "@rollup", "browser", "dist", "es", "bindings_wasm_bg.wasm"),
    "bindings_wasm_bg.wasm",
    "renderer",
  ),
  copiedArtifact(join(dependencyRoot, "@rollup", "browser", "LICENSE.md"), "LICENSE.rollup.md", "private"),
  moduleBundlerSourceArtifact,
  excludedArtifact("rings-webview-service-worker.js"),
  excludedArtifact("extension_webview_worker_modules.js"),
  excludedArtifact(join("assets", "webview-host.js")),
  excludedArtifact(join("assets", "webview-overlay.js")),
  excludedArtifact(join("assets", "webview-worker-navigation.js")),
  excludedArtifact(join("assets", "webview-worker-request.js")),
  excludedArtifact(join("assets", "webview-worker-response.js")),
];
validateExtensionRuntimeArtifactPolicy(EXTENSION_RUNTIME_ARTIFACTS);

const cargoToml = await readFile(join(projectRoot, "Cargo.toml"), "utf8");
const crateVersion = cargoToml.match(/^version\s*=\s*"([^"]+)"/m)?.[1] ?? "0.1.0";
const extensionVersion = chromeVersion(crateVersion);

const ICON_STATES = {
  neutral: {
    file: "rings",
    color: "#00e5ff",
  },
  disconnected: {
    file: "rings-disconnected",
    color: "#d8fbff",
  },
  connecting: {
    file: "rings-connecting",
    color: "#ffcb6b",
  },
  connected: {
    file: "rings-connected",
    color: "#54ffd0",
  },
} as const satisfies Record<string, IconState>;

let sourceRoot = sourceDist;
let files = await readdir(sourceRoot);
if (!files.some((file: string): boolean => file.endsWith(".js"))) {
  const stageDist = join(sourceDist, ".stage");
  const stageFiles = await readdir(stageDist).catch((): string[] => []);
  if (stageFiles.some((file: string): boolean => file.endsWith(".js"))) {
    sourceRoot = stageDist;
    files = stageFiles;
  }
}
const sourceHtml = await readFile(join(sourceRoot, "index.html"), "utf8").catch((): string => "");
const jsFile =
  entryFileFromHtml(sourceHtml, files, /import\s+init[\s\S]*?from\s+['"]([^'"]+\.js)['"]/) ??
  entryFileFromHtml(sourceHtml, files, /<link[^>]+rel="modulepreload"[^>]+href="([^"]+\.js)"/) ??
  singleFile(files, (file: string): boolean => file.endsWith(".js"), "generated JS bundle");
const wasmFile =
  entryFileFromHtml(sourceHtml, files, /module_or_path:\s*['"]([^'"]+_bg\.wasm)['"]/) ??
  entryFileFromHtml(sourceHtml, files, /<link[^>]+rel="preload"[^>]+href="([^"]+_bg\.wasm)"/) ??
  singleFile(files, (file: string): boolean => file.endsWith("_bg.wasm"), "generated wasm bundle");

await rm(extensionDist, { force: true, recursive: true });
await mkdir(extensionDist, { recursive: true });
await cp(join(sourceRoot, jsFile), join(extensionDist, jsFile));
await cp(join(sourceRoot, wasmFile), join(extensionDist, wasmFile));
await cp(join(projectRoot, "assets"), join(extensionDist, "assets"), { recursive: true });
await Promise.all(
  excludedExtensionOutputs()
    .filter((output: string): boolean => output.startsWith(`assets${sep}`) || output.startsWith("assets/"))
    .map((output: string): Promise<void> => rm(join(extensionDist, output))),
);

await writeFile(join(extensionDist, "index.html"), htmlShell(jsFile, wasmFile, { includeNodeBridge: true }), "utf8");
await writeFile(
  join(extensionDist, "offscreen.html"),
  htmlShell(jsFile, wasmFile, { includeNodeBridge: false }),
  "utf8",
);
await writeFile(join(extensionDist, "bootstrap.js"), bootstrapScript(jsFile, wasmFile), "utf8");
await copyExtensionRuntimeAssets();
await writeExtensionIcons();
await writeFile(
  join(extensionDist, "manifest.json"),
  `${JSON.stringify(manifest(extensionVersion), null, 2)}\n`,
  "utf8",
);
await verifyExtensionOmitsWebviewGatewayAssets();

console.log(`Packaged Chrome MV3 extension at ${extensionDist}`);

/**
 * Resolves the frontend project root from either source or generated script paths.
 */
function frontendProjectRoot(currentScriptDir: string): string {
  const parentDir = dirname(currentScriptDir);
  if (basename(parentDir) === ".generated") {
    return resolve(parentDir, "..");
  }
  return resolve(currentScriptDir, "..");
}

/** Declares a compiler-emitted runtime module whose output retains its filename. */
function compiledArtifact(output: string, exposure: "private" | "renderer"): CopiedExtensionArtifact {
  return copiedArtifact(join(extensionAssets, output), output, exposure);
}

/** Declares a static runtime asset whose output retains its filename. */
function staticArtifact(output: string, exposure: "private" | "renderer"): CopiedExtensionArtifact {
  return copiedArtifact(join(staticExtensionAssets, output), output, exposure);
}

/** Declares one copied runtime artifact with an explicit output name. */
function copiedArtifact(source: string, output: string, exposure: "private" | "renderer"): CopiedExtensionArtifact {
  return { kind: "copy", source, output, exposure };
}

/** Declares one generated runtime artifact. */
function generatedArtifact(output: string, exposure: "private" | "renderer"): GeneratedExtensionArtifact {
  return { kind: "generated", output, exposure };
}

/** Declares one browser-only output forbidden from the extension package. */
function excludedArtifact(output: string): ExcludedExtensionArtifact {
  return { kind: "excluded", output };
}

/** Copies the finite runtime artifact set without embedding HTML or CSS in MTS. */
async function copyExtensionRuntimeAssets(): Promise<void> {
  const copies = EXTENSION_RUNTIME_ARTIFACTS.filter(
    (artifact: ExtensionRuntimeArtifactPolicy): artifact is CopiedExtensionArtifact => artifact.kind === "copy",
  );
  await Promise.all(
    copies.map(
      (artifact: CopiedExtensionArtifact): Promise<void> => cp(artifact.source, join(extensionDist, artifact.output)),
    ),
  );
  await writeModuleBundlerSource();
}

/** Packages the isolated Worker entry as inert source for a same-origin blob Worker. */
async function writeModuleBundlerSource(): Promise<void> {
  const source = await readFile(join(extensionAssets, "extension_webview_worker_modules.js"), "utf8");
  const moduleMarker = "export {};\n";
  if (!source.endsWith(moduleMarker)) throw new Error("isolated Worker compiler emitted an unexpected module shape");
  const classicWorkerSource = source.slice(0, -moduleMarker.length);
  const installer = `Object.defineProperty(globalThis, "__ringsWebviewModuleBundlerSource", { configurable: true, value: ${JSON.stringify(classicWorkerSource)} });\n`;
  await writeFile(join(extensionDist, moduleBundlerSourceArtifact.output), installer, "utf8");
}

/**
 * The HTTP(S) WebView host and debug overlay require a Service Worker-controlled origin.
 * Extension mode supplies its own trusted host and opaque renderer, so keep only those web-host
 * adapters out of the MV3 artifact while packaging the shared pure transforms separately.
 */
async function verifyExtensionOmitsWebviewGatewayAssets(): Promise<void> {
  await Promise.all(
    excludedExtensionOutputs().map(async (file: string): Promise<void> => {
      const found = await access(join(extensionDist, file)).then(
        (): boolean => true,
        (): boolean => false,
      );
      if (found) {
        throw new Error(`Packaged extension must not include browser-only WebView asset: ${file}`);
      }
    }),
  );
}

/** Proves unique ownership within the explicitly scoped runtime artifact policy. */
function validateExtensionRuntimeArtifactPolicy(artifacts: readonly ExtensionRuntimeArtifactPolicy[]): void {
  const outputs = artifacts.map((artifact: ExtensionRuntimeArtifactPolicy): string => artifact.output);
  if (new Set(outputs).size !== outputs.length) {
    throw new Error("Extension artifact policy contains duplicate output owners");
  }
}

/** Projects the runtime artifact policy into forbidden package outputs. */
function excludedExtensionOutputs(): readonly string[] {
  return EXTENSION_RUNTIME_ARTIFACTS.filter(
    (artifact: ExtensionRuntimeArtifactPolicy): artifact is ExcludedExtensionArtifact => artifact.kind === "excluded",
  ).map((artifact: ExcludedExtensionArtifact): string => artifact.output);
}

/**
 * Finds exactly one generated file matching a predicate.
 */
function singleFile(fileList: readonly string[], predicate: (file: string) => boolean, label: string): string {
  const matches = fileList.filter(predicate);
  if (matches.length !== 1) {
    throw new Error(`Expected one ${label} in ${sourceRoot}, found ${matches.length}`);
  }
  const [match] = matches;
  if (!match) {
    throw new Error(`Expected one ${label} in ${sourceRoot}, found none`);
  }
  return match;
}

/**
 * Extracts a generated asset filename from Trunk HTML when available.
 */
function entryFileFromHtml(html: string, fileList: readonly string[], pattern: RegExp): string | undefined {
  const match = html.match(pattern);
  const rawFile = match?.[1];
  if (!rawFile) {
    return undefined;
  }
  const file = rawFile.replace(/^\.\//, "").replace(/^\//, "");
  return fileList.includes(file) ? file : undefined;
}

/**
 * Converts a Cargo semver string into the Chrome extension version format.
 */
function chromeVersion(version: string): string {
  const parts = version.split(".").map((part: string): string => part.replace(/\D.*$/, "") || "0");
  while (parts.length < 3) {
    parts.push("0");
  }
  return parts.slice(0, 4).join(".");
}

/**
 * Writes all extension icon variants into the package directory.
 */
async function writeExtensionIcons(): Promise<void> {
  const iconsDir = join(extensionDist, "icons");
  await mkdir(iconsDir, { recursive: true });
  const iconSvg = await readFile(sourceIconSvg, "utf8");
  await writeFile(join(iconsDir, "rings.svg"), iconSvg, "utf8");
  for (const state of Object.values(ICON_STATES)) {
    const tempDir = await mkdtemp(join(tmpdir(), "rings-icon-"));
    const svgPath = join(tempDir, `${state.file}.svg`);
    try {
      await writeFile(svgPath, tintIconSvg(iconSvg, state.color), "utf8");
      for (const size of [16, 32, 48, 128]) {
        await renderSvgToPng(svgPath, join(iconsDir, `${state.file}-${size}.png`), size);
      }
    } finally {
      await rm(tempDir, { force: true, recursive: true });
    }
  }
}

/**
 * Recolors the source SVG while preserving its shape.
 */
function tintIconSvg(svg: string, color: string): string {
  const tinted = svg.replace(/\sfill="(?!none\b)[^"]*"/gi, ` fill="${color}"`);
  if (tinted !== svg) {
    return tinted;
  }
  return svg.replace(
    /<svg\b([^>]*)>/i,
    `<svg$1>\n<style>path,circle,rect,polygon,polyline,ellipse{fill:${color};}</style>`,
  );
}

/**
 * Renders one SVG icon to PNG using the first available local renderer.
 */
async function renderSvgToPng(svgPath: string, pngPath: string, size: number): Promise<void> {
  const renderers: ReadonlyArray<readonly [string, readonly string[]]> = [
    ["sips", ["-s", "format", "png", "-z", String(size), String(size), svgPath, "--out", pngPath]],
    ["rsvg-convert", ["-w", String(size), "-h", String(size), "-o", pngPath, svgPath]],
    ["magick", [svgPath, "-resize", `${size}x${size}`, pngPath]],
  ];
  const errors: string[] = [];
  for (const [command, args] of renderers) {
    try {
      await execFileAsync(command, [...args]);
      return;
    } catch (error: unknown) {
      errors.push(`${command}: ${errorMessage(error)}`);
    }
  }
  throw new Error(
    `Unable to render ${svgPath} to ${pngPath}. Tried sips, rsvg-convert, and magick.\n${errors.join("\n")}`,
  );
}

/**
 * Builds the extension page HTML without inline scripts so MV3 CSP accepts it.
 */
function htmlShell(jsFileName: string, wasmFileName: string, options: HtmlShellOptions): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Rings - A P2P network for the sovereign age</title>
    <link rel="icon" type="image/svg+xml" href="./icons/rings.svg" />
    <link rel="icon" type="image/png" sizes="16x16" href="./icons/rings-16.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="./icons/rings-32.png" />
    <link rel="apple-touch-icon" href="./icons/rings-128.png" />
    <meta name="theme-color" content="#020c10" />
    <link rel="modulepreload" href="./${jsFileName}" />
    <link rel="preload" href="./${wasmFileName}" as="fetch" type="application/wasm" />
  </head>
  <body>
    <script type="module" src="./wallet_bridge.js"></script>
    ${options.includeNodeBridge ? '<script type="module" src="./node_bridge.js"></script>' : ""}
    <script type="module" src="./bootstrap.js"></script>
  </body>
</html>
`;
}

/**
 * Builds the external bootstrap module that loads wasm-bindgen output.
 */
function bootstrapScript(jsFileName: string, wasmFileName: string): string {
  return `import init, * as bindings from "./${jsFileName}";

const wasm = await init({
  module_or_path: new URL("./${wasmFileName}", import.meta.url),
});

globalThis.wasmBindings = bindings;
globalThis.dispatchEvent(new CustomEvent("TrunkApplicationStarted", { detail: { wasm } }));
`;
}

/**
 * Builds the Chrome Manifest V3 JSON payload.
 */
function manifest(version: string): ChromeManifest {
  return {
    manifest_version: 3,
    name: "Rings Frontend",
    short_name: "Rings",
    version,
    description: "Rings browser frontend for WebRTC peer connectivity and Chord topology.",
    minimum_chrome_version: "116",
    icons: {
      16: "icons/rings-16.png",
      32: "icons/rings-32.png",
      48: "icons/rings-48.png",
      128: "icons/rings-128.png",
    },
    action: {
      default_title: "Rings",
      default_icon: {
        16: "icons/rings-disconnected-16.png",
        32: "icons/rings-disconnected-32.png",
        48: "icons/rings-disconnected-48.png",
        128: "icons/rings-disconnected-128.png",
      },
    },
    background: {
      service_worker: "service_worker.js",
      type: "module",
    },
    side_panel: {
      default_path: "index.html",
    },
    options_page: "index.html",
    permissions: [
      "activeTab",
      "declarativeNetRequestWithHostAccess",
      "offscreen",
      "scripting",
      "sidePanel",
      "storage",
      "webNavigation",
    ],
    host_permissions: ["http://*/*", "https://*/*"],
    web_accessible_resources: [
      {
        resources: EXTENSION_RUNTIME_ARTIFACTS.filter(
          (
            artifact: ExtensionRuntimeArtifactPolicy,
          ): artifact is CopiedExtensionArtifact | GeneratedExtensionArtifact =>
            artifact.kind !== "excluded" && artifact.exposure === "renderer",
        ).map((artifact: CopiedExtensionArtifact | GeneratedExtensionArtifact): string => artifact.output),
        matches: ["<all_urls>"],
      },
    ],
    content_security_policy: {
      extension_pages: "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'; frame-src 'self';",
      sandbox:
        "sandbox allow-scripts allow-forms allow-modals; default-src 'none'; base-uri 'none'; connect-src data: blob:; font-src data: blob:; form-action 'none'; frame-src 'self'; img-src data: blob:; media-src data: blob:; object-src data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline' blob:",
    },
    sandbox: {
      pages: ["webview_frame.html"],
    },
  };
}

/**
 * Converts an unknown renderer failure into a message string.
 */
function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
