// biome-ignore-all lint/complexity/useLiteralKeys: Every message enters through an unknown Worker boundary.
/** Isolated, on-demand module-graph bundler for onion-backed Workers. */

import type { WebviewCredentials } from "./webview_protocol.js";

/** Source location returned by the packaged ECMAScript module lexer. */
type ModuleImport = {
  readonly n?: string;
  readonly s: number;
  readonly e: number;
  readonly d: number;
};

/** Runtime surface of the packaged ECMAScript module lexer. */
type ModuleLexer = {
  readonly parse: (source: string) => readonly [readonly ModuleImport[], unknown];
};

/** One JavaScript chunk generated by the packaged browser Rollup runtime. */
type RollupChunk = { readonly type: "chunk"; readonly code: string };

/** Minimal browser Rollup build surface used by the module graph boundary. */
type RollupBuild = {
  readonly close: () => Promise<void>;
  readonly generate: (options: {
    readonly format: "es";
    readonly inlineDynamicImports: true;
  }) => Promise<{ readonly output: readonly (RollupChunk | { readonly type: "asset" })[] }>;
};

/** Module resolver accepted by the packaged browser Rollup runtime. */
type RollupPlugin = {
  readonly name: string;
  readonly resolveId: (
    specifier: string,
    importer: string | undefined,
  ) => Promise<string | { readonly id: string; readonly external: true }>;
  readonly load: (id: string) => Promise<string>;
};

/** Browser Rollup entry point loaded inside this pristine Worker realm. */
type RollupRuntime = {
  readonly rollup: (options: {
    readonly input: string;
    readonly plugins: readonly RollupPlugin[];
    readonly preserveEntrySignatures: false;
    readonly treeshake: false;
  }) => Promise<RollupBuild>;
};

/** Canonical dependency target paired with its gateway-provided source. */
type WorkerModuleSource = { readonly url: string; readonly source: string };

/** Module graph request accepted by one isolated parser/bundler Worker. */
type ModuleBundleRequest = {
  readonly type: "rings.worker.bundle";
  readonly mode: "module";
  readonly entryTarget: string;
  readonly entrySource: string;
  readonly credentials: WebviewCredentials;
  readonly moduleLexerUrl: string;
  readonly rollupUrl: string;
};

/** Classic graph request accepted by one isolated parser/bundler Worker. */
type ClassicBundleRequest = {
  readonly type: "rings.worker.bundle";
  readonly mode: "classic";
  readonly entryTarget: string;
  readonly entrySource: string;
  readonly credentials: "same-origin";
  readonly acornUrl: string;
};

/** Closed request algebra accepted by the isolated graph materializer. */
type BundleRequest = ModuleBundleRequest | ClassicBundleRequest;

/** Minimal ESTree node surface returned by the packaged Acorn parser. */
type AcornNode = {
  readonly type: string;
  readonly start: number;
  readonly end: number;
  readonly [key: string]: unknown;
};

/** Runtime surface of the packaged JavaScript parser. */
type AcornParser = {
  readonly parse: (
    source: string,
    options: { readonly ecmaVersion: "latest"; readonly sourceType: "script" },
  ) => unknown;
};

/** One statically named classic-worker importScripts call. */
type ClassicImportCall = {
  readonly start: number;
  readonly end: number;
  readonly specifiers: readonly string[];
};

/** Validated response to one dependency-source request. */
type SourceResponse = {
  readonly type: "rings.worker.bundle.source.response";
  readonly requestId: number;
  readonly source?: WorkerModuleSource;
  readonly error?: string;
};

/** Unique resolver slot for one in-flight dependency request. */
type PendingSource = {
  readonly resolve: (source: WorkerModuleSource) => void;
  readonly reject: (error: Error) => void;
};

let moduleLexerPromise: Promise<ModuleLexer> | undefined;
let rollupRuntimePromise: Promise<RollupRuntime> | undefined;
let acornPromise: Promise<AcornParser> | undefined;

globalThis.addEventListener("message", (event: MessageEvent<unknown>): void => {
  if (!isBundleRequest(event.data) || !event.ports[0]) return;
  const port = event.ports[0];
  void materializeWorkerGraph(event.data, port)
    .then((code: string): void => {
      port.postMessage({ type: "rings.worker.bundle.result", code });
      port.close();
    })
    .catch((error: unknown): void => {
      port.postMessage({ type: "rings.worker.bundle.result", error: errorMessage(error) });
      port.close();
    });
});

/** Selects one pure graph transform after the discriminated request is validated. */
async function materializeWorkerGraph(request: BundleRequest, sourcePort: MessagePort): Promise<string> {
  if (request.mode === "module") return bundleModuleGraph(request, sourcePort);
  const parser = await acornParser(request.acornUrl);
  const requestSource = installSourcePort(sourcePort);
  return materializeClassicImports(
    request.entryTarget,
    request.entrySource,
    requestSource,
    parser,
    new Map(),
    new Set(),
  );
}

/**
 * Bundles one finite graph after a host explicitly requests a Module Worker.
 *
 * Invariant M1: every non-local dependency is fetched only through `sourcePort`.
 * Invariant M2: every Rollup id is the canonical response URL witnessed by the host.
 * Invariant M3: this pristine realm owns Rollup initialization; authored page globals are absent.
 */
async function bundleModuleGraph(request: ModuleBundleRequest, sourcePort: MessagePort): Promise<string> {
  const sources = new Map<string, string>([[request.entryTarget, request.entrySource]]);
  const fetches = new Map<string, Promise<WorkerModuleSource>>();
  const requestSource = installSourcePort(sourcePort);
  const [lexer, runtime] = await Promise.all([moduleLexer(request.moduleLexerUrl), rollupRuntime(request.rollupUrl)]);
  const plugin = moduleGraphPlugin(request, lexer, requestSource, sources, fetches);
  const build = await runtime.rollup({
    input: request.entryTarget,
    plugins: [plugin],
    preserveEntrySignatures: false,
    treeshake: false,
  });
  try {
    const generated = await build.generate({ format: "es", inlineDynamicImports: true });
    const chunks = generated.output.filter((output): output is RollupChunk => output.type === "chunk");
    const entry = chunks.length === 1 ? chunks[0] : undefined;
    if (!entry) throw new Error("module Worker graph did not produce one entry chunk");
    return entry.code;
  } finally {
    await build.close();
  }
}

/** Creates the effect adapter between Rollup's graph walk and the trusted host. */
function moduleGraphPlugin(
  request: ModuleBundleRequest,
  lexer: ModuleLexer,
  requestSource: (target: string, credentials: WebviewCredentials) => Promise<WorkerModuleSource>,
  sources: Map<string, string>,
  fetches: Map<string, Promise<WorkerModuleSource>>,
): RollupPlugin {
  return {
    name: "rings-onion-worker-modules",
    resolveId: async (specifier: string, importer: string | undefined) => {
      if (!importer) return request.entryTarget;
      if (isLocalModuleSpecifier(specifier)) return { id: specifier, external: true };
      const target = normalizeModuleTarget(specifier, importer);
      const dependency = await fetchWorkerScriptCached(target, request.credentials, requestSource, fetches);
      rememberCanonicalSource(sources, dependency);
      return dependency.url;
    },
    load: async (id: string): Promise<string> => {
      const source = sources.get(id);
      if (source === undefined) throw new Error(`worker module source is unavailable for ${id}`);
      return prepareModuleSource(source, id, lexer);
    },
  };
}

/** Installs a finite request/response algebra over the transferred source port. */
function installSourcePort(
  port: MessagePort,
): (target: string, credentials: WebviewCredentials) => Promise<WorkerModuleSource> {
  const pending = new Map<number, PendingSource>();
  let nextRequestId = 1;
  port.addEventListener("message", (event: MessageEvent<unknown>): void => {
    const response = parseSourceResponse(event.data);
    if (!response) return;
    const slot = pending.get(response.requestId);
    if (!slot) return;
    pending.delete(response.requestId);
    if (response.source) slot.resolve(response.source);
    else slot.reject(new Error(response.error ?? "module source request failed"));
  });
  port.start();
  return (target: string, credentials: WebviewCredentials): Promise<WorkerModuleSource> => {
    const requestId = nextRequestId;
    nextRequestId += 1;
    return new Promise((resolve, reject): void => {
      pending.set(requestId, { resolve, reject });
      port.postMessage({
        type: "rings.worker.bundle.source.request",
        requestId,
        target,
        credentials,
      });
    });
  };
}

/** Preserves a one-to-one canonical URL-to-source relation inside the graph. */
function rememberCanonicalSource(sources: Map<string, string>, dependency: WorkerModuleSource): void {
  const existing = sources.get(dependency.url);
  if (existing !== undefined && existing !== dependency.source) {
    throw new Error(`worker module ${dependency.url} returned inconsistent source within one graph`);
  }
  sources.set(dependency.url, dependency.source);
}

/** Shares the in-flight onion fetch effect of one requested module target. */
async function fetchWorkerScriptCached(
  target: string,
  credentials: WebviewCredentials,
  requestSource: (target: string, credentials: WebviewCredentials) => Promise<WorkerModuleSource>,
  cache: Map<string, Promise<WorkerModuleSource>>,
): Promise<WorkerModuleSource> {
  const cached = cache.get(target);
  if (cached) return cached;
  const fetched = requestSource(target, credentials);
  cache.set(target, fetched);
  try {
    return await fetched;
  } catch (error: unknown) {
    if (cache.get(target) === fetched) cache.delete(target);
    throw error;
  }
}

/** Rejects authority-ambiguous imports and projects import.meta onto its original URL. */
function prepareModuleSource(source: string, target: string, lexer: ModuleLexer): string {
  const imports = lexer.parse(source)[0];
  const ambiguous = imports.find((entry: ModuleImport): boolean => entry.d !== -2 && !entry.n);
  if (ambiguous) throw new TypeError(`dynamic module Worker import must use a string literal in ${target}`);
  return rewriteImportMeta(source, target, imports);
}

/** Loads the complete ECMAScript lexer lazily from the validated extension URL. */
async function moduleLexer(moduleUrl: string): Promise<ModuleLexer> {
  moduleLexerPromise ??= import(moduleUrl).then((module: unknown): ModuleLexer => {
    if (!isModuleLexer(module)) throw new Error("packaged module lexer is unavailable");
    return module;
  });
  return moduleLexerPromise;
}

/** Loads Rollup lazily inside this Worker, never on ordinary WebView navigation. */
async function rollupRuntime(moduleUrl: string): Promise<RollupRuntime> {
  rollupRuntimePromise ??= import(moduleUrl).then((module: unknown): RollupRuntime => {
    if (!isRollupRuntime(module)) throw new Error("packaged module bundler is unavailable");
    return module;
  });
  return rollupRuntimePromise;
}

/** Recursively materializes statically named classic dependencies through the trusted source port. */
async function materializeClassicImports(
  target: string,
  source: string,
  requestSource: (target: string, credentials: WebviewCredentials) => Promise<WorkerModuleSource>,
  parser: AcornParser,
  fetches: Map<string, Promise<WorkerModuleSource>>,
  ancestors: ReadonlySet<string>,
): Promise<string> {
  if (ancestors.has(target)) throw new TypeError(`cyclic classic Worker dependency is unsupported at ${target}`);
  const nextAncestors = new Set(ancestors);
  nextAncestors.add(target);
  const calls = parsedClassicImportCalls(source, parser);
  const replacements = await Promise.all(
    calls.map(async (call: ClassicImportCall): Promise<readonly [ClassicImportCall, string]> => {
      const dependencies = await Promise.all(
        call.specifiers.map(async (specifier: string): Promise<string> => {
          const dependency = await fetchWorkerScriptCached(
            normalizeModuleTarget(specifier, target),
            "same-origin",
            requestSource,
            fetches,
          );
          const materialized = await materializeClassicImports(
            dependency.url,
            dependency.source,
            requestSource,
            parser,
            fetches,
            nextAncestors,
          );
          return `(0, eval)(${JSON.stringify(`${materialized}\n//# sourceURL=${dependency.url}`)});`;
        }),
      );
      return [call, dependencies.join("\n")] as const;
    }),
  );
  return rewriteClassicImports(source, replacements);
}

/** Extracts only unshadowed literal importScripts calls from a complete ESTree parse. */
function parsedClassicImportCalls(source: string, parser: AcornParser): readonly ClassicImportCall[] {
  const root = parser.parse(source, { ecmaVersion: "latest", sourceType: "script" });
  if (!isAcornNode(root)) throw new Error("packaged JavaScript parser returned an invalid syntax tree");
  const calls: ClassicImportCall[] = [];
  visitAcornTree(root, (node: AcornNode, ancestors: readonly AcornNode[]): void => {
    if (node.type !== "CallExpression" || !isGlobalImportScriptsCallee(node["callee"], ancestors)) return;
    if (!Array.isArray(node["arguments"])) throw new TypeError("invalid importScripts syntax tree");
    const specifiers = node["arguments"].map((argument: unknown): string => {
      if (!isAcornNode(argument) || argument.type !== "Literal" || typeof argument["value"] !== "string") {
        throw new TypeError("classic Worker importScripts arguments must be string literals");
      }
      return argument["value"];
    });
    calls.push({ start: node.start, end: node.end, specifiers });
  });
  return calls;
}

/** Loads Acorn only in this isolated Worker realm. */
async function acornParser(moduleUrl: string): Promise<AcornParser> {
  acornPromise ??= import(moduleUrl).then((module: unknown): AcornParser => {
    if (!isRecord(module) || typeof module["parse"] !== "function") {
      throw new Error("packaged JavaScript parser is unavailable");
    }
    return module as AcornParser;
  });
  return acornPromise;
}

/** Visits every ESTree child with its lexical ancestor path. */
function visitAcornTree(node: AcornNode, effect: (node: AcornNode, ancestors: readonly AcornNode[]) => void): void {
  const pending: { readonly node: AcornNode; readonly ancestors: readonly AcornNode[] }[] = [{ node, ancestors: [] }];
  while (pending.length > 0) {
    const entry = pending.pop();
    if (!entry) continue;
    effect(entry.node, entry.ancestors);
    const ancestors = [...entry.ancestors, entry.node];
    for (const value of Object.values(entry.node)) {
      if (isAcornNode(value)) pending.push({ node: value, ancestors });
      else if (Array.isArray(value)) {
        for (const child of value) if (isAcornNode(child)) pending.push({ node: child, ancestors });
      }
    }
  }
}

/** Narrows an unknown parser value to its finite ESTree identity. */
function isAcornNode(value: unknown): value is AcornNode {
  return (
    isRecord(value) &&
    typeof value["type"] === "string" &&
    typeof value["start"] === "number" &&
    typeof value["end"] === "number"
  );
}

/** Recognizes an unshadowed global importScripts call in identifier or member form. */
function isGlobalImportScriptsCallee(value: unknown, ancestors: readonly AcornNode[]): boolean {
  if (!isAcornNode(value)) return false;
  if (value.type === "Identifier" && value["name"] === "importScripts") {
    return !lexicalPathBinds("importScripts", ancestors);
  }
  if (value.type !== "MemberExpression" || !isAcornNode(value["object"])) return false;
  const object = value["object"];
  const objectName = object.type === "Identifier" ? object["name"] : undefined;
  if ((objectName !== "self" && objectName !== "globalThis") || lexicalPathBinds(objectName, ancestors)) return false;
  const property = value["property"];
  return (
    (value["computed"] !== true &&
      isAcornNode(property) &&
      property.type === "Identifier" &&
      property["name"] === "importScripts") ||
    (value["computed"] === true &&
      isAcornNode(property) &&
      property.type === "Literal" &&
      property["value"] === "importScripts")
  );
}

/** Returns whether an enclosing lexical or hoisted scope owns a name before the global scope. */
function lexicalPathBinds(name: unknown, ancestors: readonly AcornNode[]): boolean {
  if (typeof name !== "string") return false;
  for (let index = ancestors.length - 1; index >= 0; index -= 1) {
    const scope = ancestors[index];
    if (!scope) continue;
    if (scope.type === "CatchClause" && patternBinds(scope["param"], name)) return true;
    if (isLoopScope(scope) && declarationBinds(scope["init"] ?? scope["left"], name, false)) return true;
    if (scope.type === "SwitchStatement" && switchScopeBinds(scope, name)) return true;
    if (scope.type === "BlockStatement" && blockScopeBinds(scope, name)) return true;
    if (isFunctionNode(scope) && functionScopeBinds(scope, name)) return true;
    if (scope.type === "Program") return programScopeBinds(scope, name);
  }
  return false;
}

/** Returns whether a function's parameters, name, or hoisted declarations bind a name. */
function functionScopeBinds(scope: AcornNode, name: string): boolean {
  if (patternBinds(scope["id"], name)) return true;
  if (
    Array.isArray(scope["params"]) &&
    scope["params"].some((parameter: unknown): boolean => patternBinds(parameter, name))
  ) {
    return true;
  }
  return isAcornNode(scope["body"]) && containsHoistedBinding(scope["body"], name);
}

/** Returns whether a Program owns a top-level lexical or hoisted binding. */
function programScopeBinds(scope: AcornNode, name: string): boolean {
  return blockScopeBinds(scope, name) || containsHoistedBinding(scope, name);
}

/** Returns whether direct statements in one block-like body declare a name. */
function blockScopeBinds(scope: AcornNode, name: string): boolean {
  return (
    Array.isArray(scope["body"]) &&
    scope["body"].some((statement: unknown): boolean => declarationBinds(statement, name, true))
  );
}

/** Returns whether a switch's shared lexical scope declares a name in one case. */
function switchScopeBinds(scope: AcornNode, name: string): boolean {
  if (!Array.isArray(scope["cases"])) return false;
  return scope["cases"].some(
    (entry: unknown): boolean =>
      isAcornNode(entry) &&
      Array.isArray(entry["consequent"]) &&
      entry["consequent"].some((statement: unknown): boolean => declarationBinds(statement, name, true)),
  );
}

/** Finds function/program-hoisted declarations without crossing child functions. */
function containsHoistedBinding(root: AcornNode, name: string): boolean {
  const pending = Object.values(root).flatMap((value: unknown): AcornNode[] => acornChildren(value));
  while (pending.length > 0) {
    const current = pending.pop();
    if (!current) continue;
    if (current.type === "FunctionDeclaration") {
      if (patternBinds(current["id"], name)) return true;
      continue;
    }
    if (isFunctionNode(current)) continue;
    if (current.type === "VariableDeclaration" && current["kind"] === "var" && declarationBinds(current, name, true)) {
      return true;
    }
    for (const value of Object.values(current)) pending.push(...acornChildren(value));
  }
  return false;
}

/** Returns all direct ESTree children carried by one unknown property. */
function acornChildren(value: unknown): AcornNode[] {
  if (isAcornNode(value)) return [value];
  return Array.isArray(value) ? value.filter(isAcornNode) : [];
}

/** Returns whether one declaration node introduces a binding. */
function declarationBinds(value: unknown, name: string, includeVar: boolean): boolean {
  if (!isAcornNode(value)) return false;
  if (value.type === "VariableDeclaration") {
    if (!includeVar && value["kind"] === "var") return false;
    return (
      Array.isArray(value["declarations"]) &&
      value["declarations"].some((entry: unknown): boolean => isAcornNode(entry) && patternBinds(entry["id"], name))
    );
  }
  return (value.type === "FunctionDeclaration" || value.type === "ClassDeclaration") && patternBinds(value["id"], name);
}

/** Returns whether a destructuring or scalar binding pattern contains a name. */
function patternBinds(value: unknown, name: string): boolean {
  if (!isAcornNode(value)) return false;
  if (value.type === "Identifier") return value["name"] === name;
  if (value.type === "RestElement") return patternBinds(value["argument"], name);
  if (value.type === "AssignmentPattern") return patternBinds(value["left"], name);
  if (value.type === "ArrayPattern") {
    return (
      Array.isArray(value["elements"]) && value["elements"].some((entry: unknown): boolean => patternBinds(entry, name))
    );
  }
  if (value.type === "ObjectPattern" && Array.isArray(value["properties"])) {
    return value["properties"].some((entry: unknown): boolean => {
      if (!isAcornNode(entry)) return false;
      return entry.type === "RestElement" ? patternBinds(entry["argument"], name) : patternBinds(entry["value"], name);
    });
  }
  return false;
}

/** Returns whether one ancestor introduces a loop-local lexical scope. */
function isLoopScope(value: AcornNode): boolean {
  return value.type === "ForStatement" || value.type === "ForInStatement" || value.type === "ForOfStatement";
}

/** Returns whether one ESTree node is a function scope. */
function isFunctionNode(value: AcornNode): boolean {
  return (
    value.type === "FunctionDeclaration" ||
    value.type === "FunctionExpression" ||
    value.type === "ArrowFunctionExpression"
  );
}

/** Applies non-overlapping classic call spans from right to left. */
function rewriteClassicImports(
  source: string,
  replacements: readonly (readonly [ClassicImportCall, string])[],
): string {
  return [...replacements]
    .sort(
      ([left]: readonly [ClassicImportCall, string], [right]: readonly [ClassicImportCall, string]): number =>
        right.start - left.start,
    )
    .reduce(
      (output: string, [call, replacement]: readonly [ClassicImportCall, string]): string =>
        `${output.slice(0, call.start)}${replacement}${output.slice(call.end)}`,
      source,
    );
}

/** Returns whether a module specifier requires no network authority. */
function isLocalModuleSpecifier(specifier: string): boolean {
  const lower = specifier.trim().toLowerCase();
  return lower.startsWith("blob:") || lower.startsWith("data:");
}

/** Restricts dependency resolution to the HTTPS onion-exit carrier. */
function normalizeModuleTarget(specifier: string, importer: string): string {
  const target = new URL(specifier, importer);
  if (target.protocol !== "https:") throw new TypeError(`unsupported worker module protocol ${target.protocol}`);
  target.username = "";
  target.password = "";
  return target.href;
}

/** Rewrites each import.meta occurrence to one extensible module-local object. */
function rewriteImportMeta(source: string, target: string, imports: readonly ModuleImport[]): string {
  const locations = imports.filter((entry: ModuleImport): boolean => entry.d === -2);
  if (locations.length === 0) return source;
  const binding = importMetaBinding(source);
  const rewritten = [...locations]
    .sort((left: ModuleImport, right: ModuleImport): number => right.s - left.s)
    .reduce(
      (output: string, entry: ModuleImport): string => `${output.slice(0, entry.s)}${binding}${output.slice(entry.e)}`,
      source,
    );
  return `${importMetaDeclaration(binding, target)}\n${rewritten}`;
}

/** Chooses a module-local metadata binding that cannot capture authored code. */
function importMetaBinding(source: string): string {
  let suffix = 0;
  while (true) {
    const binding = `__ringsWorkerImportMeta${suffix}`;
    if (!source.includes(binding)) return binding;
    suffix += 1;
  }
}

/** Builds the writable and extensible metadata object required by native ESM. */
function importMetaDeclaration(binding: string, target: string): string {
  const encodedTarget = JSON.stringify(target);
  return `const ${binding}={__proto__:null,url:${encodedTarget},resolve:(value)=>new URL(String(value),${encodedTarget}).href};`;
}

/** Narrows the only accepted host-to-bundler request. */
function isBundleRequest(value: unknown): value is BundleRequest {
  if (!isRecord(value) || value["type"] !== "rings.worker.bundle") return false;
  if (typeof value["entryTarget"] !== "string" || typeof value["entrySource"] !== "string") return false;
  if (value["mode"] === "classic") {
    return value["credentials"] === "same-origin" && isExtensionModuleUrl(value["acornUrl"], "acorn.mjs");
  }
  return (
    value["mode"] === "module" &&
    isWebviewCredentials(value["credentials"]) &&
    isExtensionModuleUrl(value["moduleLexerUrl"], "es-module-lexer.js") &&
    isExtensionModuleUrl(value["rollupUrl"], "rollup.browser.js")
  );
}

/** Accepts only a named packaged runtime dependency, never an authored URL. */
function isExtensionModuleUrl(value: unknown, file: string): value is string {
  if (typeof value !== "string") return false;
  try {
    const url = new URL(value);
    return url.protocol === "chrome-extension:" && url.pathname === `/${file}`;
  } catch (_error) {
    return false;
  }
}

/** Parses one dependency response before it reaches the graph core. */
function parseSourceResponse(value: unknown): SourceResponse | undefined {
  if (
    !isRecord(value) ||
    value["type"] !== "rings.worker.bundle.source.response" ||
    !Number.isSafeInteger(value["requestId"]) ||
    typeof value["requestId"] !== "number"
  ) {
    return undefined;
  }
  const source = value["source"];
  if (isRecord(source) && typeof source["url"] === "string" && typeof source["source"] === "string") {
    return {
      type: "rings.worker.bundle.source.response",
      requestId: value["requestId"],
      source: {
        url: source["url"],
        source: source["source"],
      },
    };
  }
  return {
    type: "rings.worker.bundle.source.response",
    requestId: value["requestId"],
    error: typeof value["error"] === "string" ? value["error"] : "module source response is invalid",
  };
}

/** Validates the callable lexer surface without an unchecked type assertion. */
function isModuleLexer(value: unknown): value is ModuleLexer {
  return isRecord(value) && typeof value["parse"] === "function";
}

/** Validates the callable Rollup surface without an unchecked type assertion. */
function isRollupRuntime(value: unknown): value is RollupRuntime {
  return isRecord(value) && typeof value["rollup"] === "function";
}

/** Returns whether a value is one finite credentials mode. */
function isWebviewCredentials(value: unknown): value is WebviewCredentials {
  return value === "omit" || value === "same-origin" || value === "include";
}

/** Narrows one unknown message value to an object record. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/** Projects unknown resolver failures into stable diagnostics. */
function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
