[package]
name = "rings-transport"
description = "Transport layer implementation for Rings Core"
readme = "README.md"
categories = ["network-programming", "cryptography", "wasm", "webrtc"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
# Include nothing by default
default = ["tokio/time", "tokio-util"]
dummy = ["webrtc", "rand", "lazy_static"]
native-webrtc = ["webrtc"]
web-sys-webrtc = ["wasm-bindgen", "js-sys", "web-sys", "wasm-bindgen-futures"]

[dependencies]
# Dependencies for native-webrtc feature
tokio = { version = "1.47.0", optional = true }
tokio-util = { version = "0.7.8", optional = true }
webrtc = { workspace = true, optional = true }

# Dependencies for dummy feature
lazy_static = { version = "1.4.0", optional = true }
rand = { version = "0.8.5", optional = true, features = ["getrandom"] }

# Dependencies for web-sys-webrtc feature
js-sys = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { version = "0.3.64", optional = true, features = [
    "Blob",
    "MessageEvent",
    "RtcConfiguration",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcDataChannelState",
    "RtcIceCredentialType",
    "RtcIceGatheringState",
    "RtcIceServer",
    "RtcPeerConnection",
    "RtcPeerConnectionState",
    "RtcSdpType",
    "RtcSessionDescription",
    "RtcSessionDescriptionInit",
    "RtcStatsReport",
    "Window",
    "WorkerGlobalScope",
    "ServiceWorkerGlobalScope",
] }

# Common dependencies
async-trait = { workspace = true }
bincode = "1.3.3"
bytes = { version = "1.4.0", features = ["serde"] }
chrono = { version = "0.4.30", features = ["wasmbind"] }
dashmap = "5.5.1"
serde = "1.0.183"
serde_json = "1.0.106"
thiserror = "1.0.47"
tracing = "0.1.37"
url = { version = "2.4.0", features = ["serde"] }


[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
futures = "0.3.28"
tokio = { version = "1.47.0", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "1.47", default-features = false, features = ["rt", "sync", "macros", "test-util"] }