[package]
name = "rings-snark-extension"
description = "SNARK extension application for Rings Network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["node"]
node = [
    "rings-core/default",
    "rings-derive/default",
    "rings-node/node",
]
browser_default = ["browser"]
browser_chrome_test = ["browser"]
browser = [
    "dep:js-sys",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "rings-core/wasm",
    "rings-derive/wasm",
    "rings-node/browser",
]

[dependencies]
async-trait = { workspace = true }
bytes = { version = "1.2.1", features = ["serde"] }
dashmap = "5"
js-sys = { workspace = true, optional = true }
rings-codec = { workspace = true }
rings-core = { workspace = true, default-features = false }
rings-derive = { workspace = true, default-features = false }
rings-node = { path = "../../crates/node", version = "0.16.0", default-features = false }
rings-snark = { workspace = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.70"
thiserror = "1"
tracing = "0.1.37"
uuid = { version = "0.8.2" }
wasm-bindgen = { workspace = true, features = ["serde-serialize"], optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }

[dev-dependencies]
tokio = { version = "1.13.0", features = ["macros", "rt-multi-thread"] }
wasm-bindgen-test = { workspace = true }
